"""
http code and message
"""


TIMESTAMP_INVALID_CODE = 203
TIMESTAMP_INVALID_MESSAGE = u'timestamp不合法'

TIMESTAMP_EXPIRED_CODE = 204
TIMESTAMP_EXPIRED_MESSAGE = u'timestamp超过30s'

TIMESTAMP_HEADER_NOT_FOUND_CODE = 205
TIMESTAMP_HEADER_NOT_FOUND_MESSAGE = u'未传入timestamp头信息'

ACCESSKEY_HEADER_NOT_FOUND_CODE = 206
ACCESSKEY_HEADER_NOT_FOUND_MESSAGE = u'未传入AccessKey头信息'

SIGNATURE_HEADER_NOT_FOUND_CODE = 207
SIGNATURE_HEADER_NOT_FOUND_MESSAGE = u'未传入Signature头信息'

HOST_HEADER_NOT_FOUND_CODE = 208
HOST_HEADER_NOT_FOUND_MESSAGE = u'未传入Hots头信息'

VERSION_HEADER_NOT_FOUND_CODE = 208
VERSION_HEADER_NOT_FOUND_MESSAGE = u'未传入version头信息'

ACCESSKEY_NOT_FOUND_CODE = 209
ACCESSKEY_NOT_FOUND_MESSAGE = u'未找到相关accessKey'

SIGNATURE_INVALID_CODE = 403
SIGNATURE_INVALID_MESSAGE = u'签名认证不通过'

UNKNOW_EXCEPTION_CODE = 500
UNKNOW_EXCEPTION_MESSAGE = u'未知错误'

